### ISSUE TITLE
Cors issue on "/Request" api route

### ISSUE THREAD

**Issue by flothjl** [antistud/november#25]
![image](https://user-images.githubusercontent.com/16403356/70865709-1634d180-1f26-11ea-8925-3b2530379517.png)

**Comment by antistud** [comment]
Are you seeing the app on the hosted instance?  I am not.  
![image](https://user-images.githubusercontent.com/16789785/70866741-f526ad80-1f32-11ea-91ee-3dd61782e290.png)
